apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-jenkins-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-jenkins-demo
  template:
    metadata:
      labels:
        app: docker-k8s-jenkins-demo
    spec:
      containers:
        - name: docker-k8s-jenkins-demo
          image: rahulbagli/docker-k8s-jenkins-demo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
