apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-jenkins-demo
spec:
  type: NodePort
  selector:
    app: docker-k8s-jenkins-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
